// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sf/substreams/sink/database/v1/database.proto

package pbdatabase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation defines the type of database operation to perform on the row.
type TableChange_Operation int32

const (
	// OPERATION_UNSPECIFIED should not be used in practice.
	// This exists as the protobuf default to ensure consumers explicitly set the operation type.
	TableChange_OPERATION_UNSPECIFIED TableChange_Operation = 0
	// OPERATION_CREATE inserts a new row into the table.
	// Will fail if a row with the same primary key already exists.
	TableChange_OPERATION_CREATE TableChange_Operation = 1
	// OPERATION_UPDATE modifies an existing row in the table.
	// Will fail if no row with the specified primary key exists.
	TableChange_OPERATION_UPDATE TableChange_Operation = 2
	// OPERATION_DELETE removes a row from the table.
	// Will fail if no row with the specified primary key exists.
	TableChange_OPERATION_DELETE TableChange_Operation = 3
	// OPERATION_UPSERT inserts a new row or updates an existing row.
	// If a row with the primary key exists, it updates; otherwise, it creates.
	//
	// The upsert might not be supported by all drivers the sink supports,
	// refer to https://github.com/streamingfast/substreams-sink-sql for
	// which drivers support it.
	//
	// At time of writing, the Postgres driver supports was the only one supporting
	// it.
	TableChange_OPERATION_UPSERT TableChange_Operation = 4
)

// Enum value maps for TableChange_Operation.
var (
	TableChange_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
		4: "OPERATION_UPSERT",
	}
	TableChange_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_CREATE":      1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
		"OPERATION_UPSERT":      4,
	}
)

func (x TableChange_Operation) Enum() *TableChange_Operation {
	p := new(TableChange_Operation)
	*p = x
	return p
}

func (x TableChange_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableChange_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_sink_database_v1_database_proto_enumTypes[0].Descriptor()
}

func (TableChange_Operation) Type() protoreflect.EnumType {
	return &file_sf_substreams_sink_database_v1_database_proto_enumTypes[0]
}

func (x TableChange_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableChange_Operation.Descriptor instead.
func (TableChange_Operation) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{1, 0}
}

// UpdateOp defines how the field value should be combined with existing data during UPSERT operations.
// Only applies when TableChange.operation is OPERATION_UPSERT.
// Allows for advanced merge behaviors beyond simple replacement.
type Field_UpdateOp int32

const (
	// UPDATE_OP_UNSPECIFIED should not be used in practice.
	// This exists as the protobuf default to ensure consumers explicitly set the update operation type.
	Field_UPDATE_OP_UNSPECIFIED Field_UpdateOp = 0
	// UPDATE_OP_SET replaces the column value with the provided value (default behavior).
	// SQL equivalent: column = value
	Field_UPDATE_OP_SET Field_UpdateOp = 1
	// UPDATE_OP_ADD adds the provided value to the existing column value.
	// Useful for counters and numeric accumulation.
	// SQL equivalent: column = COALESCE(column, 0) + value
	Field_UPDATE_OP_ADD Field_UpdateOp = 2
	// UPDATE_OP_MAX sets the column to the maximum of existing value and provided value.
	// Useful for tracking high-water marks or maximum observed values.
	// SQL equivalent: column = GREATEST(COALESCE(column, value), value)
	Field_UPDATE_OP_MAX Field_UpdateOp = 3
	// UPDATE_OP_MIN sets the column to the minimum of existing value and provided value.
	// Useful for tracking low-water marks or minimum observed values.
	// SQL equivalent: column = LEAST(COALESCE(column, value), value)
	Field_UPDATE_OP_MIN Field_UpdateOp = 4
	// UPDATE_OP_SET_IF_NULL sets the column to the provided value only if it's currently NULL.
	// Preserves the first non-NULL value and prevents subsequent overwrites.
	// SQL equivalent: column = COALESCE(column, value)
	Field_UPDATE_OP_SET_IF_NULL Field_UpdateOp = 5
)

// Enum value maps for Field_UpdateOp.
var (
	Field_UpdateOp_name = map[int32]string{
		0: "UPDATE_OP_UNSPECIFIED",
		1: "UPDATE_OP_SET",
		2: "UPDATE_OP_ADD",
		3: "UPDATE_OP_MAX",
		4: "UPDATE_OP_MIN",
		5: "UPDATE_OP_SET_IF_NULL",
	}
	Field_UpdateOp_value = map[string]int32{
		"UPDATE_OP_UNSPECIFIED": 0,
		"UPDATE_OP_SET":         1,
		"UPDATE_OP_ADD":         2,
		"UPDATE_OP_MAX":         3,
		"UPDATE_OP_MIN":         4,
		"UPDATE_OP_SET_IF_NULL": 5,
	}
)

func (x Field_UpdateOp) Enum() *Field_UpdateOp {
	p := new(Field_UpdateOp)
	*p = x
	return p
}

func (x Field_UpdateOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field_UpdateOp) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_sink_database_v1_database_proto_enumTypes[1].Descriptor()
}

func (Field_UpdateOp) Type() protoreflect.EnumType {
	return &file_sf_substreams_sink_database_v1_database_proto_enumTypes[1]
}

func (x Field_UpdateOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field_UpdateOp.Descriptor instead.
func (Field_UpdateOp) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{3, 0}
}

// DatabaseChanges represents a collection of table changes that should be applied to a database.
// This is the top-level message that Substreams modules output when using the database sink.
// All changes within a DatabaseChanges message are typically applied within a single transaction.
type DatabaseChanges struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table_changes is an ordered list of changes to apply to database tables.
	// The changes are applied in the order they appear in this list.
	TableChanges  []*TableChange `protobuf:"bytes,1,rep,name=table_changes,json=tableChanges,proto3" json:"table_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseChanges) Reset() {
	*x = DatabaseChanges{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseChanges) ProtoMessage() {}

func (x *DatabaseChanges) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseChanges.ProtoReflect.Descriptor instead.
func (*DatabaseChanges) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseChanges) GetTableChanges() []*TableChange {
	if x != nil {
		return x.TableChanges
	}
	return nil
}

// TableChange represents a single change operation (CREATE, UPDATE, DELETE, or UPSERT) on a database table row.
// Each TableChange must specify the table name, primary key, operation type, and the fields to modify.
type TableChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is the name of the database table to modify.
	// This should match the actual table name in your database schema.
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// primary_key identifies the row to operate on. Use either a single primary key string
	// or a composite primary key for tables with multi-column primary keys.
	//
	// Types that are valid to be assigned to PrimaryKey:
	//
	//	*TableChange_Pk
	//	*TableChange_CompositePk
	PrimaryKey isTableChange_PrimaryKey `protobuf_oneof:"primary_key"`
	// ordinal provides ordering information for this change within the block.
	// Changes with lower ordinal values are applied before changes with higher values.
	// This ensures deterministic ordering when multiple changes affect the same or related data.
	Ordinal uint64 `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// operation specifies what type of change to apply to the table row.
	Operation TableChange_Operation `protobuf:"varint,4,opt,name=operation,proto3,enum=sf.substreams.sink.database.v1.TableChange_Operation" json:"operation,omitempty"`
	// fields contains the column values to set or update.
	// For CREATE and UPSERT operations, these are the values for the new/updated row.
	// For UPDATE operations, these are the columns to modify.
	// For DELETE operations, fields may be empty or contain old values for logging/auditing.
	Fields        []*Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableChange) Reset() {
	*x = TableChange{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableChange) ProtoMessage() {}

func (x *TableChange) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableChange.ProtoReflect.Descriptor instead.
func (*TableChange) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{1}
}

func (x *TableChange) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *TableChange) GetPrimaryKey() isTableChange_PrimaryKey {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *TableChange) GetPk() string {
	if x != nil {
		if x, ok := x.PrimaryKey.(*TableChange_Pk); ok {
			return x.Pk
		}
	}
	return ""
}

func (x *TableChange) GetCompositePk() *CompositePrimaryKey {
	if x != nil {
		if x, ok := x.PrimaryKey.(*TableChange_CompositePk); ok {
			return x.CompositePk
		}
	}
	return nil
}

func (x *TableChange) GetOrdinal() uint64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *TableChange) GetOperation() TableChange_Operation {
	if x != nil {
		return x.Operation
	}
	return TableChange_OPERATION_UNSPECIFIED
}

func (x *TableChange) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type isTableChange_PrimaryKey interface {
	isTableChange_PrimaryKey()
}

type TableChange_Pk struct {
	// pk is used for tables with a single-column primary key.
	// The value should be the primary key value as a string.
	Pk string `protobuf:"bytes,2,opt,name=pk,proto3,oneof"`
}

type TableChange_CompositePk struct {
	// composite_pk is used for tables with multi-column primary keys.
	// Provides a map of column names to their values.
	CompositePk *CompositePrimaryKey `protobuf:"bytes,6,opt,name=composite_pk,json=compositePk,proto3,oneof"`
}

func (*TableChange_Pk) isTableChange_PrimaryKey() {}

func (*TableChange_CompositePk) isTableChange_PrimaryKey() {}

// CompositePrimaryKey represents a primary key composed of multiple columns.
// Use this when your table has a multi-column primary key instead of a single primary key column.
type CompositePrimaryKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keys is a map from column name to column value for each part of the composite primary key.
	// All values are represented as strings and will be converted to the appropriate type by the sink.
	// Example: {"user_id": "123", "post_id": "456"} for a table with composite primary key (user_id, post_id)
	Keys          map[string]string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositePrimaryKey) Reset() {
	*x = CompositePrimaryKey{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositePrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositePrimaryKey) ProtoMessage() {}

func (x *CompositePrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositePrimaryKey.ProtoReflect.Descriptor instead.
func (*CompositePrimaryKey) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{2}
}

func (x *CompositePrimaryKey) GetKeys() map[string]string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Field represents a single column value in a table row.
// Contains the column name, value, and an update operation mode for UPSERT operations.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the column name in the database table.
	// Must match the actual column name in your database schema.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value is the value to set for this column.
	// All values are represented as strings and will be converted to the appropriate database type.
	// For numeric types, use string representation (e.g., "123", "45.67").
	// For NULL values, leave this field empty or unset.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// update_op specifies how to merge this field's value during UPSERT operations.
	// Defaults to UPDATE_OP_SET if not specified.
	// Ignored for CREATE, UPDATE, and DELETE operations.
	UpdateOp      Field_UpdateOp `protobuf:"varint,4,opt,name=update_op,json=updateOp,proto3,enum=sf.substreams.sink.database.v1.Field_UpdateOp" json:"update_op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{3}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Field) GetUpdateOp() Field_UpdateOp {
	if x != nil {
		return x.UpdateOp
	}
	return Field_UPDATE_OP_UNSPECIFIED
}

var File_sf_substreams_sink_database_v1_database_proto protoreflect.FileDescriptor

const file_sf_substreams_sink_database_v1_database_proto_rawDesc = "" +
	"\n" +
	"-sf/substreams/sink/database/v1/database.proto\x12\x1esf.substreams.sink.database.v1\"c\n" +
	"\x0fDatabaseChanges\x12P\n" +
	"\rtable_changes\x18\x01 \x03(\v2+.sf.substreams.sink.database.v1.TableChangeR\ftableChanges\"\xcc\x03\n" +
	"\vTableChange\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x10\n" +
	"\x02pk\x18\x02 \x01(\tH\x00R\x02pk\x12X\n" +
	"\fcomposite_pk\x18\x06 \x01(\v23.sf.substreams.sink.database.v1.CompositePrimaryKeyH\x00R\vcompositePk\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x04R\aordinal\x12S\n" +
	"\toperation\x18\x04 \x01(\x0e25.sf.substreams.sink.database.v1.TableChange.OperationR\toperation\x12=\n" +
	"\x06fields\x18\x05 \x03(\v2%.sf.substreams.sink.database.v1.FieldR\x06fields\"~\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x03\x12\x14\n" +
	"\x10OPERATION_UPSERT\x10\x04B\r\n" +
	"\vprimary_key\"\xa1\x01\n" +
	"\x13CompositePrimaryKey\x12Q\n" +
	"\x04keys\x18\x01 \x03(\v2=.sf.substreams.sink.database.v1.CompositePrimaryKey.KeysEntryR\x04keys\x1a7\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12K\n" +
	"\tupdate_op\x18\x04 \x01(\x0e2..sf.substreams.sink.database.v1.Field.UpdateOpR\bupdateOp\"\x8c\x01\n" +
	"\bUpdateOp\x12\x19\n" +
	"\x15UPDATE_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rUPDATE_OP_SET\x10\x01\x12\x11\n" +
	"\rUPDATE_OP_ADD\x10\x02\x12\x11\n" +
	"\rUPDATE_OP_MAX\x10\x03\x12\x11\n" +
	"\rUPDATE_OP_MIN\x10\x04\x12\x19\n" +
	"\x15UPDATE_OP_SET_IF_NULL\x10\x05J\x04\b\x03\x10\x04R\told_valueB\xb8\x02\n" +
	"\"com.sf.substreams.sink.database.v1B\rDatabaseProtoP\x01Zfgithub.com/streamingfast/substreams-sink-database-changes/pb/sf/substreams/sink/database/v1;pbdatabase\xa2\x02\x04SSSD\xaa\x02\x1eSf.Substreams.Sink.Database.V1\xca\x02\x1eSf\\Substreams\\Sink\\Database\\V1\xe2\x02*Sf\\Substreams\\Sink\\Database\\V1\\GPBMetadata\xea\x02\"Sf::Substreams::Sink::Database::V1b\x06proto3"

var (
	file_sf_substreams_sink_database_v1_database_proto_rawDescOnce sync.Once
	file_sf_substreams_sink_database_v1_database_proto_rawDescData []byte
)

func file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP() []byte {
	file_sf_substreams_sink_database_v1_database_proto_rawDescOnce.Do(func() {
		file_sf_substreams_sink_database_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_database_v1_database_proto_rawDesc), len(file_sf_substreams_sink_database_v1_database_proto_rawDesc)))
	})
	return file_sf_substreams_sink_database_v1_database_proto_rawDescData
}

var file_sf_substreams_sink_database_v1_database_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sf_substreams_sink_database_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sf_substreams_sink_database_v1_database_proto_goTypes = []any{
	(TableChange_Operation)(0),  // 0: sf.substreams.sink.database.v1.TableChange.Operation
	(Field_UpdateOp)(0),         // 1: sf.substreams.sink.database.v1.Field.UpdateOp
	(*DatabaseChanges)(nil),     // 2: sf.substreams.sink.database.v1.DatabaseChanges
	(*TableChange)(nil),         // 3: sf.substreams.sink.database.v1.TableChange
	(*CompositePrimaryKey)(nil), // 4: sf.substreams.sink.database.v1.CompositePrimaryKey
	(*Field)(nil),               // 5: sf.substreams.sink.database.v1.Field
	nil,                         // 6: sf.substreams.sink.database.v1.CompositePrimaryKey.KeysEntry
}
var file_sf_substreams_sink_database_v1_database_proto_depIdxs = []int32{
	3, // 0: sf.substreams.sink.database.v1.DatabaseChanges.table_changes:type_name -> sf.substreams.sink.database.v1.TableChange
	4, // 1: sf.substreams.sink.database.v1.TableChange.composite_pk:type_name -> sf.substreams.sink.database.v1.CompositePrimaryKey
	0, // 2: sf.substreams.sink.database.v1.TableChange.operation:type_name -> sf.substreams.sink.database.v1.TableChange.Operation
	5, // 3: sf.substreams.sink.database.v1.TableChange.fields:type_name -> sf.substreams.sink.database.v1.Field
	6, // 4: sf.substreams.sink.database.v1.CompositePrimaryKey.keys:type_name -> sf.substreams.sink.database.v1.CompositePrimaryKey.KeysEntry
	1, // 5: sf.substreams.sink.database.v1.Field.update_op:type_name -> sf.substreams.sink.database.v1.Field.UpdateOp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sf_substreams_sink_database_v1_database_proto_init() }
func file_sf_substreams_sink_database_v1_database_proto_init() {
	if File_sf_substreams_sink_database_v1_database_proto != nil {
		return
	}
	file_sf_substreams_sink_database_v1_database_proto_msgTypes[1].OneofWrappers = []any{
		(*TableChange_Pk)(nil),
		(*TableChange_CompositePk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_database_v1_database_proto_rawDesc), len(file_sf_substreams_sink_database_v1_database_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_sink_database_v1_database_proto_goTypes,
		DependencyIndexes: file_sf_substreams_sink_database_v1_database_proto_depIdxs,
		EnumInfos:         file_sf_substreams_sink_database_v1_database_proto_enumTypes,
		MessageInfos:      file_sf_substreams_sink_database_v1_database_proto_msgTypes,
	}.Build()
	File_sf_substreams_sink_database_v1_database_proto = out.File
	file_sf_substreams_sink_database_v1_database_proto_goTypes = nil
	file_sf_substreams_sink_database_v1_database_proto_depIdxs = nil
}
