// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/sink/database/v1/database.proto

pub mod table_change {
    #[allow(unused_imports)]
    use super::*;
    /// primary_key identifies the row to operate on. Use either a single primary key string
    /// or a composite primary key for tables with multi-column primary keys.
    #[derive(Clone, PartialEq, Debug)]
    pub enum PrimaryKey {
        Pk(::buffa::alloc::string::String),
        CompositePk(
            ::buffa::alloc::boxed::Box<super::super::super::CompositePrimaryKey>,
        ),
    }
    impl ::buffa::Oneof for PrimaryKey {}
    impl From<super::super::super::CompositePrimaryKey> for PrimaryKey {
        fn from(v: super::super::super::CompositePrimaryKey) -> Self {
            Self::CompositePk(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::CompositePrimaryKey>
    for ::core::option::Option<PrimaryKey> {
        fn from(v: super::super::super::CompositePrimaryKey) -> Self {
            Self::Some(PrimaryKey::from(v))
        }
    }
}
