// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/sink/database/v1/database.proto

pub mod table_change {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum PrimaryKey<'a> {
        Pk(&'a str),
        CompositePk(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CompositePrimaryKeyView<'a>,
            >,
        ),
    }
}
