// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.substreams.sink.database.v1.database.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.sink.database.v1.database.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("sf.substreams.sink.database.v1.database.__view_oneof.rs");
        }
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.sink.database.v1.database.__lazy_view.rs");
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.sink.database.v1.database.__oneof.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::DatabaseChangesView;
#[doc(inline)]
pub use self::__buffa::view::DatabaseChangesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::DatabaseChangesLazyView;
#[doc(inline)]
pub use self::__buffa::view::TableChangeView;
#[doc(inline)]
pub use self::__buffa::view::TableChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TableChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::CompositePrimaryKeyView;
#[doc(inline)]
pub use self::__buffa::view::CompositePrimaryKeyOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CompositePrimaryKeyLazyView;
#[doc(inline)]
pub use self::__buffa::view::FieldView;
#[doc(inline)]
pub use self::__buffa::view::FieldOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::FieldLazyView;
